CREATE TABLE [dbo].[mental_health] (
    [mental_health_id]               INT            IDENTITY (1, 1) NOT NULL,
    [patient_id]                     INT            NOT NULL,
    [encounter_id]                   INT            NOT NULL,
    [past_trauma]                    NVARCHAR (3)   NOT NULL,
    [trauma_description]             NVARCHAR (MAX) NULL,
    [trauma_severity]                NVARCHAR (20)  NULL,
    [home_office_environment]        NVARCHAR (MAX) NULL,
    [chronic_stress]                 NVARCHAR (3)   NULL,
    [stress_level]                   NVARCHAR (20)  NULL,
    [stress_symptoms]                NVARCHAR (MAX) NULL,
    [personal_trait_anger]           BIT            NULL,
    [personal_trait_short_tempered]  BIT            NULL,
    [personal_trait_quarrelsome]     BIT            NULL,
    [personal_trait_suspicious]      BIT            NULL,
    [personal_trait_greedy]          BIT            NULL,
    [personal_trait_careless]        BIT            NULL,
    [personal_trait_ambitious]       BIT            NULL,
    [personal_trait_jealous]         BIT            NULL,
    [anger_issues]                   NVARCHAR (3)   NULL,
    [anger_expression]               NVARCHAR (MAX) NULL,
    [current_situation_satisfaction] NVARCHAR (3)   NULL,
    [dissatisfaction_areas]          NVARCHAR (MAX) NULL,
    [change_readiness]               NVARCHAR (3)   NULL,
    [guilt_about_past]               NVARCHAR (3)   NULL,
    [compromise_tendency]            NVARCHAR (3)   NULL,
    [loneliness]                     NVARCHAR (3)   NULL,
    [comparison_with_others]         NVARCHAR (3)   NULL,
    [feeling_responsible]            NVARCHAR (3)   NULL,
    [anxiety]                        NVARCHAR (3)   NULL,
    [depression_symptoms]            NVARCHAR (3)   NULL,
    [created_at]                     DATETIME2 (0)  DEFAULT (sysutcdatetime()) NOT NULL,
    [updated_at]                     DATETIME2 (0)  DEFAULT (sysutcdatetime()) NOT NULL,
    [created_by]                     INT            NULL,
    [updated_by]                     INT            NULL,
    PRIMARY KEY CLUSTERED ([mental_health_id] ASC),
    CHECK ([anger_issues]=N'No' OR [anger_issues]=N'Yes'),
    CHECK ([anxiety]=N'No' OR [anxiety]=N'Yes'),
    CHECK ([change_readiness]=N'No' OR [change_readiness]=N'Yes'),
    CHECK ([chronic_stress]=N'No' OR [chronic_stress]=N'Yes'),
    CHECK ([comparison_with_others]=N'No' OR [comparison_with_others]=N'Yes'),
    CHECK ([compromise_tendency]=N'No' OR [compromise_tendency]=N'Yes'),
    CHECK ([current_situation_satisfaction]=N'No' OR [current_situation_satisfaction]=N'Yes'),
    CHECK ([depression_symptoms]=N'No' OR [depression_symptoms]=N'Yes'),
    CHECK ([feeling_responsible]=N'No' OR [feeling_responsible]=N'Yes'),
    CHECK ([guilt_about_past]=N'No' OR [guilt_about_past]=N'Yes'),
    CHECK ([loneliness]=N'No' OR [loneliness]=N'Yes'),
    CHECK ([past_trauma]=N'No' OR [past_trauma]=N'Yes'),
    CHECK ([stress_level]=N'Very_high' OR [stress_level]=N'High' OR [stress_level]=N'Moderate' OR [stress_level]=N'Low'),
    CHECK ([trauma_severity]=N'Severe' OR [trauma_severity]=N'Moderate' OR [trauma_severity]=N'Mild'),
    CONSTRAINT [FK_mental_health_encounter] FOREIGN KEY ([encounter_id]) REFERENCES [dbo].[patient_encounters] ([encounter_id]),
    CONSTRAINT [FK_mental_health_patient] FOREIGN KEY ([patient_id]) REFERENCES [dbo].[patients] ([patient_id])
);


GO
CREATE NONCLUSTERED INDEX [IX_mental_health_encounter]
    ON [dbo].[mental_health]([encounter_id] ASC);

