CREATE TABLE [dbo].[reproductive_history] (
    [reproductive_id]       INT            IDENTITY (1, 1) NOT NULL,
    [patient_id]            INT            NOT NULL,
    [sexually_satisfied]    NVARCHAR (3)   NULL,
    [intercourse_frequency] NVARCHAR (50)  NULL,
    [sexual_complaints]     NVARCHAR (50)  NULL,
    [masturbation_habit]    NVARCHAR (3)   NULL,
    [family_planning]       NVARCHAR (3)   NULL,
    [contraceptive_method]  NVARCHAR (100) NULL,
    [number_of_sons]        INT            DEFAULT ((0)) NOT NULL,
    [number_of_daughters]   INT            DEFAULT ((0)) NOT NULL,
    [total_pregnancies]     INT            DEFAULT ((0)) NOT NULL,
    [miscarriage_count]     INT            DEFAULT ((0)) NOT NULL,
    [abortion_count]        INT            DEFAULT ((0)) NOT NULL,
    [gynecological_issues]  NVARCHAR (MAX) NULL,
    [menstrual_history]     NVARCHAR (MAX) NULL,
    [last_period_date]      DATETIME2 (0)  NULL,
    [created_at]            DATETIME2 (0)  DEFAULT (sysutcdatetime()) NOT NULL,
    [updated_at]            DATETIME2 (0)  DEFAULT (sysutcdatetime()) NOT NULL,
    [created_by]            INT            NULL,
    [updated_by]            INT            NULL,
    PRIMARY KEY CLUSTERED ([reproductive_id] ASC),
    CHECK ([family_planning]=N'No' OR [family_planning]=N'Yes'),
    CHECK ([masturbation_habit]=N'No' OR [masturbation_habit]=N'Yes'),
    CHECK ([sexually_satisfied]=N'No' OR [sexually_satisfied]=N'Yes'),
    CONSTRAINT [FK_reproductive_patient] FOREIGN KEY ([patient_id]) REFERENCES [dbo].[patients] ([patient_id]),
    UNIQUE NONCLUSTERED ([patient_id] ASC)
);

